name: CRD

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download & Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chromeremotedesktophost.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/i chromeremotedesktophost.msi /quiet'

      - name: Start Chrome Remote Desktop Host
        # This step now includes the --pin argument to set the PIN non-interactively.
        run: |
          # IMPORTANT: You must generate a new authorization code for EACH run.
          # 1. Go to: https://remotedesktop.google.com/headless
          # 2. Click "Begin", "Next", and "Authorize".
          # 3. Copy the command for "Windows (CMD)" and ONLY replace the --code="..." part below.
          & "${env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AVGzR1B7ZxgsOhQbZ78A1iAuFUszq4ZjzBEJz4gYM7BJgO0VwXyURSeTVLb0xNK84HtI4g" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="$env:COMPUTERNAME" --pin=112233

      - name: Time Counter
        run: |
          # Simple PowerShell timer for 6 hours (21600 seconds)
          $startTime = Get-Date
          $endTime = $startTime.AddSeconds(21600)
          Write-Host "Timer started at $startTime"
          while ((Get-Date) -lt $endTime) {
            $elapsed = (Get-Date) - $startTime
            Write-Host "Elapsed time: $($elapsed.Hours)h $($elapsed.Minutes)m $($elapsed.Seconds)s"
            Start-Sleep -Seconds 60  # Update every minute
          }
          Write-Host "Timer completed after 6 hours at $(Get-Date)"

      - name: Keep Alive
        run: |
          # Set duration to 6 hours (21600 seconds)
          $duration = 21600
          $interval = 300  # Check every 5 minutes (300 seconds)
          $endTime = (Get-Date).AddSeconds($duration)

          Write-Host "Starting keep-alive loop for 6 hours..."
          while ((Get-Date) -lt $endTime) {
            Write-Host "Workflow is still alive at $(Get-Date)"
            Start-Sleep -Seconds $interval
          }
          Write-Host "Keep-alive completed after 6 hours."
